<!DOCTYPE html><!-- "' --></script></style></noscript></xmp>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Server Error</title>

<style>
	#error-body { background: white; width: 600px; margin: 70px auto; padding: 10px 20px }
	#error-body h1 { font: bold 47px/1.5 sans-serif; background: none; color: #333; margin: .6em 0 }
	#error-body p { font: 21px/1.5 Georgia,serif; background: none; color: #333; margin: 1.5em 0 }
	#error-body small { font-size: 70%; color: gray }
</style>

<div id="error-body">
	<h1>Padá server, něco si přej.</h1>

	<!-- <p>We're sorry! The server encountered an internal error and
	was unable to complete your request. Please try again later.</p> -->

	<p>Omlouváme se, ale server se setkal s neočekávaným interním problémem. Již jsme vyslali partu cvičenců, aby problém opravili.
	Zkuste se sem prosím vrátit později.
	</p>

	<p><small>Error 500</small></p>
</div>
